### ISSUE TITLE
TwilioWebhookAuthentication on HTTPS

### ISSUE THREAD

**Issue by maceto** [twilio/twilio-ruby#236] opened 2016-09-26 19:18 UTC
Hello,

I'm using this gem to authenticate POST from Twilio webhooks, but when change to HTTPS URL's get 403 

twilio-ruby  -v 4.13.0

``` ruby
Rack::TwilioWebhookAuthentication, "TWILIO_AUTH_TOKEN",/\/twilios\/incoming\-calls/, /\/twilios\/incoming\-calls\-status/
```

No error log just 403 response

Thanks
Martin

**Comment by lperiodbose** [comment] 2017-01-06 16:24
This is hitting me right now as well. Fails pretty silently in production. In dev, I'm getting the following stack trace...

```
Started POST "/twilio/message" for 107.20.81.246 at 2017-01-06 10:18:39 -0600
Cannot render console from 107.20.81.246! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (1.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
  
NoMethodError (undefined method `get_auth_token' for #<Rack::TwilioWebhookAuthentication:0x007fe790b16e60>):
  
twilio-ruby (4.13.0) lib/rack/twilio_webhook_authentication.rb:32:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
rollbar (2.13.3) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
rollbar (2.13.3) lib/rollbar.rb:145:in `scoped'
rollbar (2.13.3) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
rollbar (2.13.3) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
web-console (2.3.0) lib/web_console/middleware.rb:20:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-mini-profiler (0.10.1) lib/mini_profiler/profiler.rb:278:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.6.2) lib/puma/configuration.rb:225:in `call'
puma (3.6.2) lib/puma/server.rb:578:in `handle_request'
puma (3.6.2) lib/puma/server.rb:415:in `process_client'
puma (3.6.2) lib/puma/server.rb:275:in `block in run'
puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
  Rendering /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.8ms)
  Rendering /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendering /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (12.1ms)
  Rendered /Users/landric/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (93.0ms)
```

**Comment by philnash** [comment] 2017-01-10 14:34
@maceto I am so sorry I only just saw your issue here. Did you find a solution?

I wonder whether Rack is able to [pick up the protocol correctly when it tries to put together the original URL](https://github.com/twilio/twilio-ruby/blob/master/lib/rack/twilio_webhook_authentication.rb#L30). If you look at the way [Rack calculates the scheme](http://www.rubydoc.info/gems/rack/Rack%2FRequest%2FHelpers%3Ascheme) you can see that it checks a bunch of headers. Does that match your implementation or what you're getting from your web server?

**Comment by philnash** [comment] 2017-01-10 14:39
@lperiodbose It looks like your issue is somewhat different as you are getting an error.

How are you including the middleware in your application? The middleware only calls [`get_auth_token` if there is no `@auth_token` set](https://github.com/twilio/twilio-ruby/blob/master/lib/rack/twilio_webhook_authentication.rb#L32) and it only [creates the method `get_auth_token`](https://github.com/twilio/twilio-ruby/blob/master/lib/rack/twilio_webhook_authentication.rb#L23) if you provide a block for generating an auth token. It looks to me like you are perhaps doing neither thus getting this error.

**Comment by lperiodbose** [comment] 2017-01-11 16:33
@philnash In order to move forward I had to remove a few entries from `config/enviroments.production.rd` that looked like...

`config.middleware.use Rack::TwilioWebhookAuthentication, Rails.application.secrets.twilio_auth_token. '/route/to/twilio/controller`

This worked fine in 4.2.1. A bundle update to 4.13 is what caused the failures to start

Is there a new recommended way to secure this endpoint under 4.13? Had I been getting it wrong to begin with?

**Comment by philnash** [comment] 2017-01-11 22:32
@lperiodbose I could only reproduce the error you had locally by unsetting `Rails.application.secrets.twilio_auth_token`. Are you sure that secret is set on your local dev machine? 

Nothing has changed in this code between 4.2.1 and 4.13 and I just tested using 4.13 and Rails 5. It successfully authenticated a request from Twilio over HTTP and HTTPS using ngrok.

When you say it's failing in production, you mean it is returning a 403 which is unexpected. It is not throwing errors though.

Can you find out whether Rack believes your are on an HTTPS connection and not an HTTP connection? I did by logging `Rack::Request.new(env)` from a Rack middleware during the `call` method.

Once you've sorted out your secrets in development, can you test using  HTTPS forwarding from ngrok?

**Comment by 7kaji** [comment] 2017-02-09 02:11
@maceto

Hello
I encountered the same problem. 
However, I solved it, so I will write a way.

my environment
```
Twilio --> Nginx ---> Unicorn(rack)
```

By default, Nginx connects to the rack application via http connection.
Need to add the following to Nginx's conf.

```
location / {
  proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto https;
  proxy_set_header    Host $http_host;
  proxy_redirect      off;
  proxy_pass          http://upstream_server;
}
```

I hope you find it informative.

**Comment by philnash** [comment] 2017-02-13 23:12
Thanks for sharing that @7kaji!

I'm going to close this for now, but if this error is still causing anyone issues then please re-open and we will sort it.

**Closed by philnash** 2017-02-13 23:12 UTC

**Comment by natsu90** [comment] 2023-10-10 09:39
@7kaji thanks! this following line did the magic; `proxy_set_header X-Forwarded-Proto https;`
