### ISSUE TITLE
Regression in 5.9.0 from 4.13.0, URI no longer encoded

### ISSUE THREAD

**Issue by bf4** [twilio/twilio-ruby#406] opened 2018-05-13 20:10 UTC
We had a test looking for a response with code `20404`, passing in the phone number `not a phone number`
In 4.13.0 this test passed, but in 5.9.0 it raises  `#<URI::InvalidURIError: bad URI(is not URI?): https://lookups.twilio.com/v1/PhoneNumbers/not a phone number>`

tl;dr

change `lib/twilio-ruby/rest/lookups/v1/phone_number.rb#L71-L72`

```diff
+        phone_number &&= URI.encode(phone_number)
        @solution = {phone_number: phone_number, }
```

Backtrace

```
     "2.4.0/uri/rfc3986_parser.rb:67:in `split'",
     "2.4.0/uri/rfc3986_parser.rb:73:in `parse'",
     "2.4.0/uri/common.rb:231:in `parse'",
     "2.4.0/uri/common.rb:737:in `URI'",
     "gems/2.4.0/gems/faraday-0.14.0/lib/faraday/utils.rb:275:in `call'",
     "gems/2.4.0/gems/faraday-0.14.0/lib/faraday/utils.rb:275:in `URI'",
     "gems/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:477:in `proxy_for_request'",
     "gems/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:377:in `run_request'",
     "gems/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'",
     "gems/2.4.0/gems/twilio-ruby-5.9.0/lib/twilio-ruby/http/http_client.rb:38:in `_request'",
     "gems/2.4.0/gems/twilio-ruby-5.9.0/lib/twilio-ruby/http/http_client.rb:56:in `request'",
     "gems/2.4.0/gems/twilio-ruby-5.9.0/lib/twilio-ruby/rest/client.rb:74:in `request'",
     "gems/2.4.0/gems/twilio-ruby-5.9.0/lib/twilio-ruby/framework/domain.rb:22:in `request'",
     "gems/2.4.0/gems/twilio-ruby-5.9.0/lib/twilio-ruby/framework/version.rb:53:in `request'",
     "gems/2.4.0/gems/twilio-ruby-5.9.0/lib/twilio-ruby/framework/version.rb:61:in `fetch'",
     "gems/2.4.0/gems/twilio-ruby-5.9.0/lib/twilio-ruby/rest/lookups/v1/phone_number.rb:103:in `fetch'",
```

the VCR recording for the test shows what 4.13.0 was doing

```
       uri: https://lookups.twilio.com/v1/PhoneNumbers/not%20a%20phone%20number
```

## 5.9.0 is no longer URI-encoding the phone number

Here's the diff in the code:

### [4.13.0](https://github.com/twilio/twilio-ruby/blob/4.13.0/lib/twilio-ruby/rest/lookups/phone_numbers.rb)

```ruby
        full_path = "#{@path}/#{URI.encode(number)}"
        full_path << "?#{url_encode(twilify(query))}" if !query.empty?
        @instance_class.new full_path, @client
```

### [5.9.0](https://github.com/twilio/twilio-ruby/blob/5.9.0/lib/twilio-ruby/rest/lookups/v1/phone_number.rb#L71-L72)

```ruby
        @solution = {phone_number: phone_number, }
        @uri = "/PhoneNumbers/#{@solution[:phone_number]}"
```

**Comment by bf4** [comment] 2018-06-20 15:49
This seems rather straightforward. I believe I followed the contribution guidelines

**Comment by sergiopantoja** [comment] 2018-06-29 20:40
@bf4 I believe this is expected behavior now. Looks similar to https://github.com/twilio/twilio-ruby/issues/304

Not sure if this breaking change was documented anywhere, though.

**Comment by bf4** [comment] 2018-07-09 23:41
Is there a I could make PR to document this or a even a test?

**Comment by childish-sambino** [comment] 2019-08-30 22:08
Closing as a duplicate of #304 

Regarding where this could be documented, I'm not sure where that would live. I think the error thrown is reasonable in that phone numbers should not include spaces, and having the lib implicitly remove _internal_ spaces from a string input (not trimming leading/trailing) feels a bit icky.

**Comment by bf4** [comment] 2019-08-30 22:21
FWIW, the api treats `%20` differently from `+`, which I think is also an issue

**Comment by childish-sambino** [comment] 2019-09-04 20:20
@bf4 I'm not seeing that behavior currently. Just tested a lookup using a `%20` number prefix with the latest release and received a sane response.

**Comment by bf4** [comment] 2019-09-10 03:49
@childish-sambino I meant that changing from using `URI.encode`/ `URI.escape`, which is deprecated. 

As rubocop writes

>  URI.escape method is obsolete and should not be used. Instead, use CGI.escape, URI.encode_www_form or URI.encode_www_form_component depending on your specific use case.

```http
GET https://lookups.twilio.com/v1/PhoneNumbers/not%20a%20phone%20number HTTP/1.1
```

returning

```http
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{"code": 20404, "message": "The requested resource /PhoneNumbers/not a phone number was not found", "more_info": "https://www.twilio.com/docs/errors/20404","status": 404}'
```

to `CGI.escape` or some equivalent

```http
GET https://lookups.twilio.com/v1/PhoneNumbers/not+a+phone+number HTTP/1.1
```

returns

```http
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{"code": 20404, "message": "The requested resource /PhoneNumbers/not+a+phone+number
was not found", "more_info": "https://www.twilio.com/docs/errors/20404", "status": 404}'
```

which is actually ok.  I don't have the exact failing test from before. Oh well.

All is well, I guess

**Comment by bf4** [comment] 2019-09-10 13:43
Ah, here was the example where changing `URI.escape` to `CGI.escape` breaks


request

```diff
-    uri: https://lookups.twilio.com/v1/PhoneNumbers/(810)%20844-3757
+    uri: https://lookups.twilio.com/v1/PhoneNumbers/(810)+844-3757
```


response

```diff
-      code: 200
-      message: OK
+      code: 404
+      message: NOT FOUND
```

```diff
-      body: '{"caller_name": null, "country_code": "US", "phone_number": "+18108443757",
-        "national_format": "(810) 844-3757", "carrier": null, "add_ons": null, "url":
-        "https://lookups.twilio.com/v1/PhoneNumbers/+18108443757"}'
+      body: '{"code": 20404, "message": "The requested resource /PhoneNumbers/(810)+844-3757
+        was not found", "more_info": "https://www.twilio.com/docs/errors/20404", "status":
+        404}'

**Comment by childish-sambino** [comment] 2019-09-13 14:57
Ah, this is making sense now. Thanks @bf4 for the clarification. I was getting confused between the space, `+`, `%20`, and the leading country code `+` prefix.

So at one point the lib did the `URI.encode`, but that is no longer the case when we switched to auto-generating that code. There was no exceptional case added for phone numbers being part of the URL (not query or body params) so they are treated just like all other URL piece parts.

And now `URI.encode/escape` should not be used but instead use what you've sampled with `CGI.escape(phone_number).gsub("+", "%20")`.

This would allow passing phone numbers with embedded spaces (and `+`s) and ensuring they get properly encoded to `%20` since the back-end API is able to handle such inputs.

Does this all sound correct? If so, I'll work on a PR to fix this in the lib itself and upstream in the generator.

**Closed** 2019-09-13 20:08 UTC
Labels: code-generation, type: bug, type: twilio enhancement
